package pl.pjaneczek.srb.model;
// Generated 2015-11-07 15:30:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Data generated by hbm2java
 */
public class Data  implements java.io.Serializable {


     private int dataId;
     private Date data;
     private Integer movieId;

    public Data() {
    }

	
    public Data(int dataId) {
        this.dataId = dataId;
    }
    public Data(int dataId, Date data, Integer movieId) {
       this.dataId = dataId;
       this.data = data;
       this.movieId = movieId;
    }
   
    public int getDataId() {
        return this.dataId;
    }
    
    public void setDataId(int dataId) {
        this.dataId = dataId;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Integer getMovieId() {
        return this.movieId;
    }
    
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }




}


