package pl.pjaneczek.srb.model;
// Generated 2015-11-07 15:30:51 by Hibernate Tools 4.3.1



/**
 * Miejsce generated by hbm2java
 */
public class Miejsce  implements java.io.Serializable {


     private int miejsceId;
     private Integer miejsceNr;

    public Miejsce() {
    }

	
    public Miejsce(int miejsceId) {
        this.miejsceId = miejsceId;
    }
    public Miejsce(int miejsceId, Integer miejsceNr) {
       this.miejsceId = miejsceId;
       this.miejsceNr = miejsceNr;
    }
   
    public int getMiejsceId() {
        return this.miejsceId;
    }
    
    public void setMiejsceId(int miejsceId) {
        this.miejsceId = miejsceId;
    }
    public Integer getMiejsceNr() {
        return this.miejsceNr;
    }
    
    public void setMiejsceNr(Integer miejsceNr) {
        this.miejsceNr = miejsceNr;
    }




}


