package pl.pjaneczek.srb.model;
// Generated 2015-11-07 15:30:51 by Hibernate Tools 4.3.1



/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private int movieId;
     private String movieName;
     private Byte movieType;
     private Integer movieYear;
     private String opis;

    public Movie() {
    }

	
    public Movie(int movieId) {
        this.movieId = movieId;
    }
    public Movie(int movieId, String movieName, Byte movieType, Integer movieYear, String opis) {
       this.movieId = movieId;
       this.movieName = movieName;
       this.movieType = movieType;
       this.movieYear = movieYear;
       this.opis = opis;
    }
   
    public int getMovieId() {
        return this.movieId;
    }
    
    public void setMovieId(int movieId) {
        this.movieId = movieId;
    }
    public String getMovieName() {
        return this.movieName;
    }
    
    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }
    public Byte getMovieType() {
        return this.movieType;
    }
    
    public void setMovieType(Byte movieType) {
        this.movieType = movieType;
    }
    public Integer getMovieYear() {
        return this.movieYear;
    }
    
    public void setMovieYear(Integer movieYear) {
        this.movieYear = movieYear;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


