package pl.pjaneczek.srb.model;
// Generated 2015-11-07 15:30:51 by Hibernate Tools 4.3.1



/**
 * Rzad generated by hbm2java
 */
public class Rzad  implements java.io.Serializable {


     private int rzadId;
     private Integer rzadNr;

    public Rzad() {
    }

	
    public Rzad(int rzadId) {
        this.rzadId = rzadId;
    }
    public Rzad(int rzadId, Integer rzadNr) {
       this.rzadId = rzadId;
       this.rzadNr = rzadNr;
    }
   
    public int getRzadId() {
        return this.rzadId;
    }
    
    public void setRzadId(int rzadId) {
        this.rzadId = rzadId;
    }
    public Integer getRzadNr() {
        return this.rzadNr;
    }
    
    public void setRzadNr(Integer rzadNr) {
        this.rzadNr = rzadNr;
    }




}


