package pl.pjaneczek.srb.model;
// Generated 2015-11-07 15:30:51 by Hibernate Tools 4.3.1



/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private int salaId;
     private Integer salaNr;
     private Integer movieId;

    public Sala() {
    }

	
    public Sala(int salaId) {
        this.salaId = salaId;
    }
    public Sala(int salaId, Integer salaNr, Integer movieId) {
       this.salaId = salaId;
       this.salaNr = salaNr;
       this.movieId = movieId;
    }
   
    public int getSalaId() {
        return this.salaId;
    }
    
    public void setSalaId(int salaId) {
        this.salaId = salaId;
    }
    public Integer getSalaNr() {
        return this.salaNr;
    }
    
    public void setSalaNr(Integer salaNr) {
        this.salaNr = salaNr;
    }
    public Integer getMovieId() {
        return this.movieId;
    }
    
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }




}


