package pl.pjaneczek.srb.model;
// Generated 2015-11-07 15:30:51 by Hibernate Tools 4.3.1



/**
 * Time generated by hbm2java
 */
public class Time  implements java.io.Serializable {


     private int timeId;
     private String time;
     private Integer movieId;

    public Time() {
    }

	
    public Time(int timeId) {
        this.timeId = timeId;
    }
    public Time(int timeId, String time, Integer movieId) {
       this.timeId = timeId;
       this.time = time;
       this.movieId = movieId;
    }
   
    public int getTimeId() {
        return this.timeId;
    }
    
    public void setTimeId(int timeId) {
        this.timeId = timeId;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Integer getMovieId() {
        return this.movieId;
    }
    
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }




}


